### ISSUE TITLE
Error with train.py

### ISSUE THREAD

**Issue by visionresearcher** [Braamling/web-page-saliency-prediction-using-two-stage-transfer-learning#1]
Hello,

Thanks for sharing your work. I'm getting this dimension mismatch error while running train.py code:

Epoch 0/9

----------
/opt/conda/lib/python3.6/site-packages/torch/nn/modules/loss.py:443: UserWarning: Using a target size (torch.Size([10, 1, 64, 64])) that is different to the input size (torch.Size([10, 64, 64])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
Traceback (most recent call last):
  File "train.py", line 240, in <module>
    train()
  File "train.py", line 205, in train
    num_epochs=FLAGS.epochs)
  File "train.py", line 149, in train_model
    print('{} Loss: {}'.format(phase, loss.data[0]))
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number

Can you please help with the resolution.
Thanks

**Comment by visionresearcher** [comment]
Solved by changing loss.data[0] to loss.data
